### ISSUE TITLE
Crash when entering ".00" in number input

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1391]
**Describe the bug**
Received a bug report that when entering income, if you put $5000.00 (with decimals,) you get an error, but entering $5000 without decimals was fine

**To Reproduce**
1. Start an application
2. Enter income with a decimal (i.e. $5000.000)
3. See error

**Expected behavior**
No error message when using decimanls

**Screenshots**
![Error_decimals](https://user-images.githubusercontent.com/86082659/122620526-0977c900-d048-11eb-95cb-acb9ccf9263c.jpg)

**Comment by neel-a-mehta** [comment]
Reproducing / comments:

1. Creating a new program that has a number question
![image](https://user-images.githubusercontent.com/77128518/122829836-58b63780-d29c-11eb-93b4-45559c1d9c3e.png)

2. Try `500` => no problem
3. Try `500.` => no problem, saved as 500
4. Try `500.1` => form can't be submitted, error message shown saying "Please enter a valid value -- nearest are 500 and 501"
5. Try `500.0` => get error 
![image](https://user-images.githubusercontent.com/77128518/122829978-8ac79980-d29c-11eb-97c8-5ac52bafa7fd.png)
6. Try `500.00` => same thing

So we handle every floating-point value besides `.0`, `.00`, `.000`, etc. just fine. We only run into trouble with someone enters these zeroes.  My guess is that our frontend validation code sees that the inputted value is exactly equal to an integer and therefore allows it, but our backend tries parsing these things and fails because it sees that it's formatted as a float.

**Comment by hmhsu** [comment]
If anyone is working on this, please let me know. Planning to take a look today.

**Comment by neel-a-mehta** [comment]
Testing:

1. Create new program with a number input
2. Publish program
3. Log in as guest applicant
4. Try entering some numbers and seeing what happens

* `32`: ok
* `32.5`: anything after the decimal point is auto-removed from the input field
* `32.`: ok (saved as plain `32`)
* `-32`: negative number input not allowed (that should be OK, nobody needs to put in a negative number)
* `1,234`: comma auto-removed, which is ok
* `3e2`: the `e` auto-deletes everything in the field!
* `53-`: the `-` auto-deletes everything in the field!

This bug is fixed but I'll raise another one for the `e` and `-` wipings. That is probably due to a quirk of `parseInt()`.
