### ISSUE TITLE
Polish the current login screen and login experience

### ISSUE THREAD

**Issue by kendrickt** [seattle-uat/civiform#1394]
**Is your feature request related to a problem? Please describe.**
The `/loginForm` page is not styled and looks pretty awful.

From #1260, the logout link should be clearer between guests and logged in users.

From #660, admins will have a polished way to login.

**Describe the solution you'd like**
The `/loginForm` page is styled.

**Additional context**
We'd like to change behavior around logging in, guests, and browsing civiform programs. But that may be more work than we have time to do, so this is just a polish task.

**Done when**
The `/loginForm` page is styled.

**Comment by neel-a-mehta** [comment]
We might even be able to get rid of the normal login screen entirely, just dropping new visitors on the applicant homepage (the one with the list of programs). They would find login links at the top of the page (for IDCS) and bottom (for admins / ADFS). The other advantage of this is reduced drop-off, since hitting people with an auth-wall right when they join would scare some people away.

**Comment by kendrickt** [comment]
reopening for story acceptance

**Comment by kendrickt** [comment]
> We might even be able to get rid of the normal login screen entirely, just dropping new visitors on the applicant homepage (the one with the list of programs). They would find login links at the top of the page (for IDCS) and bottom (for admins / ADFS). The other advantage of this is reduced drop-off, since hitting people with an auth-wall right when they join would scare some people away.

Absolutely, but we won't be able to do implement the changes for #1377 before June 30th so this is just a polish ticket to get things good.

**Comment by neel-a-mehta** [comment]
Sounds good. New styling looks good:

![Uploading image.png…]()
