### ISSUE TITLE
Minify CSS in production

### ISSUE THREAD

**Issue by bion** [seattle-uat/civiform#1399]
The app's CSS file is currently over 4MB when served in production.

Tailwind supports removing unused styles. To do that it needs to be able to read HTML-like files that contain the class names used by the app. See https://tailwindcss.com/docs/optimizing-for-production

In CiviForm we use a Java class with public static members for referencing tailwind class names: https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/views/style/Styles.java

It's likely we can generate a manifest of class names for tailwind to read by looking for references to `Styles.*` in the application code.

**Comment by lianne-oy** [comment]
Targeting close today

**Comment by lianne-oy** [comment]
(There could be more done on this by next team, but not likely the highest priority for next team given size of benefit of additional work)

**Comment by neel-a-mehta** [comment]
Testing:

- Going to live site
- Log in as guest applicant
- Open Lighthouse
- Run performance audit
- Observe results
- Looks like the CSS file is like 1700 KB instead of the 4000+ KB it used to be. File isn't minified / uglified, but appears that unnecessary CSS has been stripped out, since the site's styling still works great.

May open another issue (for the far future) to uglify the file.
