### ISSUE TITLE
Applicant ID: Different in email vs. CSV export

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1605]
**Describe the bug**
A Program Admin receives an email when an application is submitted. That email includes an applicant ID. If the Program Admin goes into CiviForm and exports the CSV of all applications though, the applicant IDs are different (i.e. email application ID = 883; CSV export application ID = 112)

**To Reproduce**
1. Open email when new applicant submits application
2. Note the applicant ID in the email--on the Subject and first line of the email
3. Open CiviForm as Program Admin
4. Download all applications -- note that the applicant IDs are different than the one in email

**Expected behavior**
Use the same applicant ID in the email alert AND CSV export

**Screenshots**
I think this shows it well--there is an applicant ID on the email but you can see there is a different number assigned in the link

![Applicant Number Issue](https://user-images.githubusercontent.com/86082659/131404442-4cb1f36e-c8e5-4dea-a243-1de158660ab9.JPG)

**Comment by leonwong** [comment]
@elisekalstad the difference here is that there are different IDs for the applicant and the application. What's exported in the CSV are the application IDs, but the title of the email and the web view of applications have the applicant ID. Not sure why it was designed this way, since I would have thought that the application IDs would be better to use consistently, but I noticed when implementing the application sorting.

**Comment by leonwong** [comment]
Proposal from SWE standup discussion is to share the application ID in email instead of the applicant ID to make it easier for the program admin to find the specific application.
