### ISSUE TITLE
Program Admins unable to view program/applications

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1612]
**Describe the bug**
There are three program admins who are unable to view anything when logging in. They are able to login to CiviForm as program admins, but there aren't any programs for them to view. It's only happening to a small number of users--everyone else seems to be able to access their forms just fine. They are logged into VPN, tried it out on several browsers (Chrome and Edge) with the same result. I tried removing them and re-adding them--still the same result.
![Error--viewing programs and applications](https://user-images.githubusercontent.com/86082659/133146551-ba6cf425-5a5d-4c71-824f-f3f407a3824c.png)

Users: thor.peterson@seattle.gov; jen.chawlibog@seattle.gov; maria.ponce@seattle.gov

**To Reproduce**
1. Go to "Admin Login" (after logging into VPN_
2. See error -- i.e. no programs listed

**Expected behavior**
Program admins should be able to view their program and all associated applications

**Screenshots**
Attached

**Desktop (please complete the following information):**
-Tried on Chrome and Edge.

**Comment by bion** [comment]
@elisekalstad could you please take a screenshot of the CiviForm Admin page that shows these three users have been configured as admins of at least one program?

**Comment by bion** [comment]
@elisekalstad Also, if you add these same three users as admins to a program on staging, are they able to login and see it?

**Comment by elisekalstad** [comment]
Hi @bion -- Thanks for taking a look! Here is the screenshot of the admin page, attached:
![Program Admins - Test Program](https://user-images.githubusercontent.com/86082659/133167670-b19be3a0-4ec1-4f7c-99ef-f147c430c2f7.JPG)

**Comment by elisekalstad** [comment]
> @elisekalstad Also, if you add these same three users as admins to a program on staging, are they able to login and see it?

Ohh! Let me try! Hang on!

**Comment by elisekalstad** [comment]
@bion I had Thor try it out (feel free to reach out, if it's easier to talk to him directly: thor.peterson@seattle.gov).

It worked great in staging! He went to the staging site >> selected "Admin Login" in the bottom right. And was able to view the program I assigned him to as well as the applications and CSV download. (pic attached)
![Program Admin - staging Success](https://user-images.githubusercontent.com/86082659/133169004-5f48b079-5f39-4c6a-ac01-cd61f962ad75.JPG)
![Program Admin - staging Success 2](https://user-images.githubusercontent.com/86082659/133169070-2ff3a917-f762-459f-bdb6-f221b5eb738f.JPG)

**Comment by bion** [comment]
@elisekalstad I noticed that those three are the only ones with all-lowercase email addresses in the admin UI. If you change them to match the case pattern of the other addresses can they access?

**Comment by elisekalstad** [comment]
I didn’t never notice. Good eye! I asked Thor to give it another whirl. I’ll let you know what he says.

[Title: City of Seattle logo]Elise Kalstad
City of Seattle, Innovation & Performance
206-256-5515 | ***@***.******@***.***>
Learn more about Innovation & Performance: seattle.gov/innovation-performance<https://www.seattle.gov/innovation-performance>
   Facebook<https://protect2.fireeye.com/v1/url?k=daf2de2b-8569e719-daf2f69b-8697e44c76c2-ac8cbbaf40b6a748&q=1&e=a18b8788-8c55-40b3-b962-7521a34eb6bf&u=https%3A%2F%2Fwww.facebook.com%2Fseattlemayorsoffice%2F> | Twitter<https://twitter.com/CityofSeattle> | Subscribe to Mayor Durkan's E-Newsletter<http://wwwqa.seattle.gov/mayor/subscribe>

**Comment by leonwong** [comment]
Recapping standup discussion: the ask here is to make email address comparison case-insensitive. That should fix the reported issues.

**Comment by ettengererin** [comment]
There is still a bug here that was discovered during UDP launch.

*Description of the issue*
Here's what happens to a seattle.gov admin after my fix:
1. Global admin adds two admins for a program "Person.One@seattle.gov"
2. Global admin saves these emails as admins and returns to the programs page
3. Global admin clicks on Manage Admins for the program to view the saved admins. "person.one@seattle.gov" is listed. This means that the when saving an email address as an admin, all characters are saved as lowercase.
4. person.one@seattle.gov receives an email when an applicant applies to the program. When person.one clicks on the link in the email, there's an error and they are unable to sign in. When they sign in directly to civiform, they don't see the program that their lowercase email is an admin of.

We think this means that the Active Directory sign in that seattle admins use to login with civiform logs in with capitalized emails - like "Person.One@seattle.gov". 

*Possible fixes*
So we need to change emails to lower case in more places:
1. Intercept emails on login and make them lowercase. [Here](https://github.com/seattle-uat/civiform/blob/57b2dfc76d139de675e440c4b197ba2a908b4a6c/universal-application-tool-0.0.1/app/auth/CiviFormProfileAdapter.java#L55)
2.  Change existing accounts to have lowercase emails. We can go about this in two ways: 
              - Convert emails to lower case in the [java code](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/models/Account.java#L70). This option is a little clunky.
              - Modify emails in the database to be lowercase. This option takes more work and is a little scarier. 
*TODO*
- Decide which of the above two fixes to go with
- If we need a temporary bandaid fix, we can roll back my PR above and make sure Elise knows to add seattle.gov admins with a capital first letter of their first and last name.

*Priority*
This is a medium/high priority issue. For UDP launch, the two folks who need to be able to see applications are able to. However, this bug makes it so that we can't add any new seattle.gov admins to any civiform program because they will all have this same login issue. We should fix this sooner rather than later.

**Comment by leonwong** [comment]
My 2 cents:
- Technically the user portion of email addresses should be case-sensitive and the domain portion is case-insensitive
- There's a tradeoff, however, between correctness & security of case-sensitive comparison vs. the practical real-world usability of case-insensitive comparison. In the ideal world, partners could configure this for their own deployments. For Seattle, since this has come up as a bug and if Active Directory is not case-sensitive, I'd err on the side of being case-insensitive comparison, but Seattle and Rochester need to be informed and comfortable with the potential for applicant security issues.
- I think email addresses should be stored as entered (no case transformation). This allows switching case sensitivity settings later on, and will preserve users' preferences for how they want emails to look.
- It's probably not worthwhile implementing any kind of fixup for previously lower-cased admin emails -- for the number we're looking at, they can be manually corrected if desired.
- For applicants, not sure there's a good way to fix, but it won't be an issue if we go with case-insensitive comparison.

**Comment by leonwong** [comment]
Is IDCS (for resident accounts) case-insensitive? Knowing that might also make the choice easier...

**Comment by ettengererin** [comment]
Thanks for your 2 cents, Leon, super helpful. 

When I sign into my own civiform account, my username is case-insensitive. Does that answer your question? Or do we need to know if the email linked to the account is case insensitive?

**Comment by leonwong** [comment]
Was trying to figure out if IDCS would allow hijacking of accounts by users with emails that only differ in case (which would undermine any of our efforts to enforce case-sensitivity if we tried to do so).

Looks like IDCS preserves email case so if your email provider is case-sensitive (and if it's not) then everything works correctly for things like email-based password resets. It doesn't seem to care if multiple accounts with similar emails are registered, but I don't see a security problem with that. Overall, I don't see obvious ways to do hijacking via IDCS so I don't think it changes my original assessment.

Net conclusion on going w/case-insensitive comparison -
- pro: makes it easier for admins to correctly grant permissions
- con: for cases where users are on case-sensitive email systems, emails that only differ in case could register for distinct IDCS accounts that would be treated as the same by civiform... 

@ettengererin as I write this I realize that a possible solution (if we're worried about security) might be to treat admins vs. applicants differently since we're mainly trying make admin permission grants easier, but this would a more careful design (and could be confusing)...

**Comment by ettengererin** [comment]
This all makes sense... I want to check in on the overall existence/reality of case sensitive emails -- Do we know that there are any case-sensitive email providers? Or is the idea to plan for the potential edge case? I can't find any examples of case-sensitive providers.

If there's such thing as case sensitive emails or the potential for them, I wonder if we should scrap this whole effort and revert to having civiform seattle admins be added as "Person.One@seattle.gov" instead of "person.one@seattle.gov".  Seems like if there is potential for users to have case-sensitive email systems, then Civiform should be case sensitive as well. However, I am not very familiar with IDCS so I'm not sure if this logic is correct.

**Comment by elisekalstad** [comment]
Thanks for thinking about this from absolutely every possible angle. @ettengererin Is it helpful if I invite Vinay to one of our check-ins? He would be able to better speak to the IDCS logic.

**Comment by rockycodes** [comment]
Fixed by https://github.com/civiform/civiform/pull/11511
