### ISSUE TITLE
Unable to enter a number with leading zeros

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1624]
**Describe the bug**
Utility customers have account numbers that start with multiple zeros. In the "number" question type, I cannot enter an account number that starts with zeros. It deletes the leading 0 instead.

**To Reproduce**
1. Go to the UDP Test form
2. Answer the first few questions
3. Find the question asking for a utility account number
4. Try to enter "0008888888"

**Expected behavior**
Numbers could start with zeros

Could be related to bug: https://github.com/seattle-uat/civiform/issues/161

**Screenshots**
Attached
![Leading zeros](https://user-images.githubusercontent.com/86082659/134580792-a562828d-ac5e-41e7-ba15-a1d2084bce12.png)

**Comment by lindsayzad** [comment]
There are a few different possible ways to implement this.  Currently, a numberQuestion only stores a Long, which is the numberValue https://github.com/seattle-uat/civiform/blob/c6813e31d3b532b693706190e28198e2eb490e18/universal-application-tool-0.0.1/app/services/applicant/question/NumberQuestion.java#L15

This should be kept as a long to enable the different number validations that can be done on it.  However, more fields can be added to the number question to enable left padding with zeros.  This could be a 'numberStringValue', where the number is stored as a string, which retains any leading zeros.  We would verify the numberStringValue had the same numerical value as the numberValue, and store both of them.  

However, the approach I am leaning towards is to add a leftZeroPad Optional<Long> to NumberQuestion, defaulting to zero, that specifies the number of 0s to be added to the left hand side of the numberValue when it is converted to a string and either rendered in the UI or exported to the user.  When the numberValue goes to the user, it should always be converted to a string that includes this left padding element.  Taking this approach stops the same thing from being saved twice (the number as a long and as a string), so that there is no need for constant validations to make sure the two values are compatible.

**Comment by elisekalstad** [comment]
@lindsayzad --Thanks for thinking through options! I'm not sure I totally understand the options, but I think one thing to flag is that the number of leading zeros isn't always consistent--for example, utility accounts may start with three zeros or two zeros. So the solution would need to be flexible enough to capture a not-consistent pattern. (If that makes sense!)

**Comment by lindsayzad** [comment]
Yeah! Both options would be able to support that :)

**Comment by ettengererin** [comment]
Thanks for outlining all these options, Lindsay!

Question about the leftZeroPad -- would this affect the applicant UI at all? Or does everything happen in the background? This option sounds reasonable to me and as long as it doesn't affect the applicant UI, I think my vote is LGTM.

**Comment by lindsayzad** [comment]
Good question Erin.  I imagine this being similar to the way that a name question stores first, middle, and last name separately, or an address question stores the city, street, and state all separately.  
https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/applicant/question/NameQuestion.java#L22
https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/applicant/question/AddressQuestion.java#L25

Although it's stored like that in the DB, when it gets rendered to users on the UI or exported to a csv it is combined into one complete answer value.  The user would not have visibility into this structure, and would only see the abstracted end result
