### ISSUE TITLE
Programs Missing/Duplicate (Resident view)

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1713]
**Describe the bug**
If a resident logs in to CiviForm with an existing account, the programs displayed are incorrect. For example, it lists the ORCA Middle School program twice and the Parks Childcare program is left off. If a resident logs in as a guest though, the correct programs display.

**To Reproduce**
1. Log in to an existing account (or create a new one!)
2. View the programs listed
3. See "ORCA Opportunity" listed twice. And "Park Child Care Scholarship" missing
4. See attachments
[Error_Programs missing when logged in.pdf](https://github.com/seattle-uat/civiform/files/7585164/Error_Programs.missing.when.logged.in.pdf)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bion** [comment]
I tried logging in as a guest and with an IDCS account and was unable to reproduce this behavior.

There's some logic on that page regarding programs that are in an active/draft state. Have there been changes published since this was reported?

![image](https://user-images.githubusercontent.com/473671/142955323-6af49665-fde7-40e9-9033-bb361efe5577.png)

**Comment by elisekalstad** [comment]
Hi @bion, thanks for taking a look. I re-published all programs about an hour ago. But I'm still able to replicate the issue now.

**Comment by ettengererin** [comment]
I am also unable to reproduce this behavior - I logged in as a guest and with an IDCS account. @elisekalstad can you check one more time and see if this is still happening?

Looking into the logic that Bion mentioned above.

**Comment by elisekalstad** [comment]
> 

Hi @ettengererin - Yeah, I'm still getting the error when I login with an IDCS account.
![Dupe program 11 29 21](https://user-images.githubusercontent.com/86082659/143942080-28ed626a-2a89-4651-b9e8-7b06659138ae.JPG)

**Comment by elisekalstad** [comment]
> > 
> 
> Hi @ettengererin - Yeah, I'm still getting the error when I login with an IDCS account. ![Dupe program 11 29 21](https://user-images.githubusercontent.com/86082659/143942080-28ed626a-2a89-4651-b9e8-7b06659138ae.JPG)

...but I'm now noticing that if I scroll down a bit, the Parks and Rec program is listed under "new programs".

**Comment by ettengererin** [comment]
That's helpful to know re the "new programs" section. Thanks Elise!

**Comment by ettengererin** [comment]
The Parks and Rec program is listed under "New programs" because you haven't started that application yet. All the other apps you've started are in the "Continue" section. **This behavior is expected**.

**The unexpected behavior** is the duplicate ORCA opportunity programs. @elisekalstad does clicking "Continue" on both of those versions work? I.e. click continue on both the first and last ORCA programs, and see if it goes to the application where you left off. Please let me know what the result is here!

**Comment by elisekalstad** [comment]
> 

Hi @ettengererin -- I clicked continue on both ORCA programs and it was pre-filled with my "test" data on both. They looked just the same, attached.
![Duplicate program - started app](https://user-images.githubusercontent.com/86082659/143967586-6fc432fe-e6da-4f8e-b688-9679d6a0c887.JPG)
