### ISSUE TITLE
Ability to customize text & logo for different cities

### ISSUE THREAD

**Issue by sussman** [seattle-uat/civiform#1876]
The phrase "Seattle" (and Seattle's logo) are currently hardcoded.
We need to abstract this so other cities can do minimal branding:

- Find the hardcoded text 'Seattle', turn it into an environment variable that is part of initial deployment config.
- Find the hardcoded logo for Seattle, turn it into another environment variable that references an image file under version control.
- Put the logos under version control (e.g. in a logos/ directory)

**Comment by sussman** [comment]
FYI:  Rochester has provided a logo to Google Fellowship within their sharepoint area.

**Comment by baipai** [comment]
About customize, here are some other parts to be consider. Although we can still using the same setting, but I believe is better to make certain decision upfront to make it more consistent
rather than spend more time to deal it later on:

- **Font, color, icon** : Right now, the font, the color style, and parts of icons all use Seattle's style, which means, it uses Seattle font, Seattle color and some Seattle icons(icon mixed with some Seattle and some others).

**Language**
The 8 languages right now are based on Seattle’s language preference, different cities have different language preferences.






Questions to think about:
If we stay in the same setting, how will other parts affect later on? will it cost more time and energy on it? are there any limitations? how far do we want the cities to be customized? will there be more cities? how are we going to scale?

**Comment by goldblatt** [comment]
We discussed and for standing ROC up we don't need to edit the fonts/colors just update the images. We are also going to put the roc images in the civiform repo instead of linking out (or sort out CORS issues with having a remote image location)
