### ISSUE TITLE
Enumeration Screen Redirects Incorrectly

### ISSUE THREAD

**Issue by glorialiou** [seattle-uat/civiform#1885]
From Brenda: When you add an enumeration screen, it takes you to the last screen in the program instead of the new created repeater screen).

Screenshot attached.
<img width="1045" alt="Enumeration issue" src="https://user-images.githubusercontent.com/11811064/152845930-2c98b189-baba-4f47-b1c1-0e72fa8e774e.png">

**Comment by clouser2** [comment]
This occurs since the block creation handler always redirects to the last block definition in the program ([code](https://github.com/seattle-uat/civiform/blob/6a76fe2c1571e027bfb8312def9080a15c077dd3/universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlocksController.java#L75-L87)). Non-enumerator blocks are always added to the end of the list, so this is the correct behavior in that case. For enumerators though, the newly added repeated screen would be added as the last block for the enumerator's parent block.

Presently, the updated program is returned from `ProgramService.addRepeatedBlockToProgram`  `ProgramService.addBlockToProgram`. This path is the only current callsite. To fix this, we can return a tuple of the Program as well as the newly added block. Then when creating the redirect URL, the new block can be used instead. There will need to be some adjustments in the error case, since this also displays errors by rendering a form using the last block in the program ([code](https://github.com/seattle-uat/civiform/blob/6a76fe2c1571e027bfb8312def9080a15c077dd3/universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlocksController.java#L84-L85)).
