### ISSUE TITLE
Validation error messages for applicants are mixed between server and client-side rendering

### ISSUE THREAD

**Issue by cassandralfernandes** [seattle-uat/civiform#1944]
For some question types, validation error messages are rendered on the server, for others they are rendered on the client-side using JavaScript. This causes a bug where two questions on the same [screen/block](https://screen.corp.google.com/block) with validations handled in different places can cause:

1. applicant attempts to submit question answers
2. applicant sees error messages for client-side rendered questions
3. applicant corrects their answers as prompted
4. applicant attempts to submit again
5. applicant sees a new set of error messages they haven't see yet
6. The solution is to move all error message presentation into the server.

**Comment by sussman** [comment]
Consensus from Bion/Susan/Ben:  the best solution for now is to go through every question-type, remove any client-side validation discovered, and then reimplement it in the server.  (Someday there may be an effort to rewrite the whole client-side architecture, but that's not happening soon.)

**Comment by clouser2** [comment]
I did some investigation and took a few notes.

**Background / Motivation**

Most of the client-side validation occurs in [validation.ts](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/assets/javascripts/validation.ts), which is a script that is [included in applicant forms](https://github.com/seattle-uat/civiform/blob/4e3f04ed954eaf0638b89a1eb8b14b2388748e74/universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java#L92). This replicates a fair amount of the logic already implemented server-side.

Example validation for "Name" question types:
*   [Client-side](https://github.com/seattle-uat/civiform/blob/40a7ad3b942a58cbd477a7e9646160ff3ec970e1/universal-application-tool-0.0.1/app/assets/javascripts/validation.ts#L495-L506)
*   [Server-side](https://github.com/seattle-uat/civiform/blob/40a7ad3b942a58cbd477a7e9646160ff3ec970e1/universal-application-tool-0.0.1/app/services/applicant/question/NameQuestion.java#L55-L56)

Server-side validation will always be necessary. Conversely, client-side validation isn't strictly required. Client-side advantages include 1) reducing the number of round-trips to the server for invalid input and 2) eventually allowing for real-time validation of the form ([example](https://github.com/seattle-uat/civiform/blob/40a7ad3b942a58cbd477a7e9646160ff3ec970e1/universal-application-tool-0.0.1/app/assets/javascripts/validation.ts#L3-L9)). That said, this also introduces a bit of extra complexity since the validation logic needs to be duplicated across the server and client. Additionally, if there's complex validation that's only implemented server-side, it can lead to behavior as described in the original issue where the user sees one set of validation errors (from client-side validation), fixes them, then sees a new wave of validation errors (generated server-side).

Per the [previous decision](https://github.com/seattle-uat/civiform/issues/1944#issuecomment-1076753220), we desire to remove the client-side logic in validation.ts entirely and instead focus on ensuring the server-side validation is the source of truth. Should client-side validation be desired in the future, an approach where the validation logic for each question type is consolidated with the server-side logic could be pursued. This would reduce the chances of inconsistently implementing validation.

**Proposed Implementation**

A typical pattern for question types is to not perform validation if the question hasn't been "answered" ([NameQuestion](https://github.com/seattle-uat/civiform/blob/40a7ad3b942a58cbd477a7e9646160ff3ec970e1/universal-application-tool-0.0.1/app/services/applicant/question/NameQuestion.java#L61)). When rendering the field in the form, all validation error messages tend to be unconditionally included but hidden based on whether there are any errors in the source question type ([NameQuestionRenderer](https://github.com/seattle-uat/civiform/blob/40a7ad3b942a58cbd477a7e9646160ff3ec970e1/universal-application-tool-0.0.1/app/views/questiontypes/NameQuestionRenderer.java#L37-L38)). Passing these hidden validation error messages in the resulting HTML allows the client-side validation to unhide them when it detects an error ([validation.ts](https://github.com/seattle-uat/civiform/blob/40a7ad3b942a58cbd477a7e9646160ff3ec970e1/universal-application-tool-0.0.1/app/assets/javascripts/validation.ts#L495-L499)).

Given the above, if we were to simply delete validation.ts, the applicant experience would change from displaying validation errors for unaswered questions to just showing a "field is required" message. As such, in addition to confirming that all client-side validation is in fact implemented server-side, we'll also want to ensure that forms rendered as part of an attempted submit always display errors. This can be achieved by piping an additional parameter to `ApplicantProgramBlockEditView.render()` when [being called due to a validation error](https://github.com/seattle-uat/civiform/blob/40a7ad3b942a58cbd477a7e9646160ff3ec970e1/universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramBlocksController.java#L365). A "successful" result here would be to remove all of the logic in validation.ts with no user-visible changes.

**Comment by clouser2** [comment]
Thinking on this a bit more. Having client-side validation hopefully reduces user frustration since we can continue moving towards giving real-time feedback when a given answer doesn't validate (i.e. input provided and an error message is immediately shown rather than upon submit).

Some concrete steps we could make here to ensure consistent client-side / server-side validation follow. Note that I think the following doesn't preclude us from any refactorings to make the form more accessible.

## Augment browser-based tests to exercise server-side only validation
The issue here stems from the fact that we have some validation only implemented on the client-side and some validation only implemented on the server-side. To ensure we don't have gaps in coverage, we can ensure we have a browser test for each question type that exercises all things we want to validate. We could additionally run it with and without client-side validation enabled in order to ensure that both the server and client are consistent.

## Reduce custom validation by making use of HTML Form Validation APIs
Regarding client-side validation, I propose trying to reduce the amount of custom logic for validation and trying to leverage HTML Form Validation APIs ([MDN doc](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation#using_built-in_form_validation)). Due to this being pure HTML, it would likely be more compatible with screen readers and other assistive technologies.

## Generalize pattern for associating errors with a field
`Question.java` is an interface that has `getQuestionErrors()` and `getAllTypeSpecificErrors()`. Both return a set of validation error messages to be presented to the user. The former is meant to be top-level validations for the entire question while the latter is meant to be specific to each field (e.g. street address line 1). However, when a field specific error is rendered server-side, we use the question-specific implementation in order to render a specific error ([example](https://github.com/seattle-uat/civiform/blob/daf89b213cebaf3f0eab5785fe5bf3a0f4954f88/universal-application-tool-0.0.1/app/views/questiontypes/NameQuestionRenderer.java#L37-L38)). Additionally, this is often hidden by default with the assumption that the client-side validation will unhide it ([example](https://github.com/seattle-uat/civiform/blob/daf89b213cebaf3f0eab5785fe5bf3a0f4954f88/universal-application-tool-0.0.1/app/assets/javascripts/validation.ts#L495-L499)). This pattern doesn't currently support multiple potential validation failures for the same field.

A proposal for how we could share validation presentation between server and client would be:
*   Remove `Question.getQuestionErrors` / `Question.getAllTypeSpecificErrors`
*   Add `Question.getAllValidationErrorMessages` - returns a mapping of all potential validation error messages, regardless of whether the question actually has the specific validation error or not. The specific error types directly mirror the attributes from the browser's [ValidityState](http://go/mdn/API/ValidityState) object. Note that a top-level error for the question itself would be keyed by the empty string rather than a subfield within the question.
    ```
    {
      "first_name": {
        "valueMissing": "Please enter your first name.",
        "rangeUnderflow": "Name must be more than 0 characters."
      },
    }
    ```
*   Add `Question.getValidationErrors()` - returns a map keyed by the field whose values indicate the set of potential error types returned by `Question.getAllValidationErrorMessages`. (e.g. `"first_name": ["not_present"]}`)
*   Relevant validation attributes are set on the field input. All error messages are sent in a hidden div from the relevant question renderer potentially with a data attribute indicating what error they're for. Any results from `Question.getAllValidationErrorMessages` are made visible by default.
    ```
    <label for="first-name">First Name</label>
    <input type="text" name="first-name" required minlength=1 />
    <div class="errors">
      <span class="hidden" data-errormessage-path="first_name.valueMissing">Please enter your first name.</span>
      <span class="hidden show" data-errormessage-path="first_name.rangeUnderflow">Name must be more than 1 characters.</span>
    </div>
    ```
* Client-side, we can check the [ValidityState](http://go/mdn/API/ValidityState) of a given element and unhide the relevant error message based on what validation failed.

### Custom validation

Custom validation logic may still be necessary if the native form controls don't support it. If that's the case, the above can be extended to have new error message keys. Server-side validation can continue to unhide the corresponding hidden span. Client-side, custom logic will need to be written. Hopefully this can be based on the presence of a data-attribute on the relevant input as well. Concretely, the above for a custom field validation type.

* `Question.getAllValidationErrorMessages()`
  ```
  {
      "first_name": {
        "aCustomValidator": "Names containing numbers must include numbers divisible by 3."
      },
  }
  ```
* Returned HTML:
  ```
  <label for="first-name">First Name</label>
  <input type="text" name="first-name" data-custom-validators="aCustomValidator" />
  <div class="errors">
    <span class="hidden show" data-errormessage-path="first_name.aCustomValidator">Names containing numbers must include numbers divisible by 3.</span>
  </div>
  ```
* Client-side validation would need to be adjusted to implement such a validator as well. The key distinction here is that client-side validation would be based on attributes on the element rather than having potentially duplicated question-specific logic.

## Implementation / Sequencing

This could be implemented on a question by question basis by:
* Update validation.ts so that client-side validation can be disabled (only needed once)
* Ensuring a question-specific browser test exists that covers all of the validation we care about and also exercises the question with client-side validation disabled.
* Add whatever pieces of the above plan are necessary to convert the question type to work server-side
* Remove the question-specific validation from `validation.ts`
