### ISSUE TITLE
Error for all admins

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#2179]
**Describe the bug**
All Program and CiviForm Admins are unable to access CiviForm. I attached the error message. Residents are still able to login and submit applications. First time error was reported was 5:00 pm on Friday, 3/25.

**To Reproduce**
1. Go to https://civiform.seattle.gov
2. Click on "Admin"
3. See error

**Screenshots**
Attached
![Error for admin](https://user-images.githubusercontent.com/86082659/160423311-db03f908-62a1-43e0-8700-99289618828e.JPG)

**Comment by gwendolyngoetz** [comment]
Logs are showing "Question not found for Program 590". I'm gathering more details right now.

**Comment by elisekalstad** [comment]
> Logs are showing "Question not found for Program 590". I'm gathering more details right now.

I was working on a program Friday afternoon... I probably triggered it. It's the Ride Now program for SDOT.

**Comment by gwendolyngoetz** [comment]
Here are the relevant id's:

- program 590
- version 228 obsolete
- version 229 active
- question 226 obsolete
- question 928 active

The program's block_definition had a reference to an obsoleted question (q226). The fix was to update the old question id in the block_definition and replace it with the active version question id (928).

Linking this to #2047 since they may be related.

**Comment by shanemc-goog** [comment]
I've figured out the root cause of this issue.

Repo:
1. Publish a program (ID 1 for example) that uses a question (ID 30 for example).
2. Open the Admin Program page and Questions page in 2 tabs.
3. In the Question tab, make a new version of the question (ID 31)
Notice: A DRAFT of the program (ID 2) is made that now references the new question version ID 31

4. In the Programs tabs, make a new version of the program.
Notice: The Draft of the program now refers to the original version of the program. ID 30

By have the Program tab cached, the page only know about Active Program ID 1, if you were to refresh it would then know about Draft program ID 2

I'm not exactly sure what's happening, but seemingly in Step 4 the configuration from ID 1 (With Question ID 30) is copied into ID 2.  When we publish, Question ID 30 is made Obsolete, and Question ID 31 and Program ID 2 are made ACTIVE.  So not Program ID 2 references an obsolete question ID 30.


The fix could come in a few forms.

1. When the user tries to "make a new version" and a draft exists, detect that and show the user a message that there's already a draft.
2. When the user tries to "make a new version" and a draft exists, load the actual draft and display it seamlessly to the user.
