### ISSUE TITLE
UAT admin can add static text/images to forms in addition to standard question types

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#241]
The UAT admin can specify arbitrary text and images in addition to normal question types.

Like in Google Forms, it sometimes helps to have helper text and images sprinkled throughout a form.

Note that this isn't rich-text-formatted; this is just plain text. We can auto-format URLs as hyperlinks, though.

**Comment by neel-a-mehta** [comment]
The text part of this is more important; the image part can come later.

**Comment by neel-a-mehta** [comment]
Promoting the priority of this one because partner and CiviForm admins really want to see this feature.

**Comment by neel-a-mehta** [comment]
To be clear, the way this works: instead of adding a Text or Number or Date question, you can add a Static Content snippet where you can just show arbitrary text. (Think of it like a Text input, but without the input field!)

**Comment by AWBaumann** [comment]
I'm trying to split this into multiple smaller issues, but the way I see it we have:

1. Create a **Static Content** question type that's always answered and has no input options. 
2. Format the static option question so that it supports advanced formatting (like the program description field).
3. Add options for inserting images with advanced formatting.
4. Add `use advanced formatting` checkbox to all other question types.
5. Perform formatting in JS so that we can see the advanced formatting in question previews.

1 and 2 are almost complete.
3 - 5 are also relatively straight forward.

**Comment by lianne-oy** [comment]
Should be complete soon - PR out for review
