### ISSUE TITLE
Double clicking on "Submit" should not create/submit 2 applications

### ISSUE THREAD

**Issue by glorialiou** [seattle-uat/civiform#2469]
If a user clicks on the "Submit" button X # of times during application submission, we create/submit X applications. We discovered this while practicing for the Bloomington UXR, when we clicked "Submit" 5 times and 5 applications were created / the Application ID # went up by 5. Some users are used to double clicking to take action, so this is something we should think about. Maybe we can disable the "Submit" button after the first click?

**Comment by clouser2** [comment]
A low-effort solution could be to add a handler for the form on `submit` and then disable the corresponding button to prevent double submission. The only thing to make sure of is that any HTML form validation (e.g. `required` attribute on input elements)  occurs before this event. Otherwise, any client-side validation may disable the button and keep it "wedged".

A potential compromise would be to disable the button for X seconds on form submit, then re-enable it.

I'm happy to send out a PR for this shortly given 1) perceived low effort and 2) surprising UX when double-clicking.

**Comment by bion** [comment]
@clouser2 this sounds like a good solution to me!
