### ISSUE TITLE
"Skip" doesn't let you skip the question if it's required for File Uploads

### ISSUE THREAD

**Issue by glorialiou** [seattle-uat/civiform#2472]
Another behavior we found surprising when playing with the UXR prototype. For document/file uploads, we saw that there was a "Skip" button, which helps with the case where the applicant cannot upload the file at the moment for whatever reason. But then the applicant actually can't skip the question if it's required: clicking on "Skip" shows a "This question is required." error. I don't think this makes sense and we should discuss intended behavior!

**Comment by clouser2** [comment]
We have different strategies for rendering the file upload form for Azure / AWS. For AWS, we don't render the "Skip" button for an optional file upload question ([code](https://github.com/seattle-uat/civiform/blob/47632149215ba8242ce0e9a40e14e56ee52a35d5/server/app/views/AwsFileUploadViewStrategy.java#L112-L115)). The issue here is that our upload strategy for Azure doesn't replicate this logic ([code](https://github.com/seattle-uat/civiform/blob/47632149215ba8242ce0e9a40e14e56ee52a35d5/server/app/views/AzureFileUploadViewStrategy.java#L115-L119)).

A quick fix is straightforward and low-effort - replicate that logic. There's a fair amount of opportunity here to share some of the rendering logic to avoid these types of issues. I'll go with the most expedient fix to unblock this scenario.
