### ISSUE TITLE
Canonically required questions

### ISSUE THREAD

**Issue by goldblatt** [seattle-uat/civiform#2484]
There are some top level questions all deployments must have:
- name
- DOB

**Comment by goldblatt** [comment]
cc @swatkat1

**Comment by goldblatt** [comment]
we probably want to document and make sure that future deployments use these

**Comment by goldblatt** [comment]
cc @azizova-leyla this is the canonically required fields issue i mentioned in our meeting

**Comment by goldblatt** [comment]
@clouser2

**Comment by bion** [comment]
from duplicate: 


CiviForm application code assumes that there will be a question with question name "Name" and therefore the path applicant.name in order to display the applicant's name in the navigation header.

At the moment this requires the admin to manually create this question. We should seed the database with this question so it is guaranteed to be there for new deployments. We should also document this in both technical and user documentation.

See https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/WellKnownPaths.java
