### ISSUE TITLE
Civiform admin can add show/hide logic in form builder

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#322]
On each block, they'd be able to specify when the block should be shown to the applicant: always, or only if certain criteria are met.

If they specify that certain criteria should be met, we will open up an area where they can define the criteria. Criteria would be of one of these formats:

* If `answer X` is less than, equal to, not equal to, or greater than `value Y` (for numbers)
* If `answer X` contains, doesn't contain, equals, or does not equal `value Y` (for text)
* If `condition A` and/or `condition B`

For example:

* If `income` is less than `$50,000`
* If `city` is not `Seattle`
* If `age` is greater than `5` _and_ `number of family members` is equal to `3`

We'd probably need to have a series of dropdowns to let people build these expressions, and some way for people to create multiple rows or dropdowns to specify combinations like "and"s and "or"s. It's going to be quite messy, unfortunately.

## Examples / proofs of concept

We're going to have to build a Boolean Logic engine, basically. The good news is that there are several examples of good UI/UX for this, such as this one: https://ux.stackexchange.com/questions/1737/intuitive-interface-for-composing-boolean-logic

**Comment by lianne-oy** [comment]
On track to be done on time (mid next week).

**Comment by carolinedanzi** [comment]
### Test Cases

**Applicant View**
1. Applicant answers a block so that a later block is hidden
2. Applicant answers a block so that a later block is shown
3. Applicant answers a block so a predicate block is shown, then goes back and modifies their answer so the block is then hidden. The hidden, answered block should not show in the applicant summary nor be submitted with their application
4. Applicant answers a block so a predicate block is hidden, then goes back and modifies their answer so the block is now shown. They must answer this block in order to submit their application

**Admin View**
1. An admin can add a simple predicate for a block that depends on an earlier question
2. An admin can add a complex predicate using and/or
3. If an admin reorders blocks, they get a warning if a block with a predicate moves to an illegal state (i.e. the question it depends on no longer exists in an earlier block)
4. If an admin removes a question from a block that a later predicate depends on, they see a warning or cannot perform the question removal

**Comment by natsid** [comment]
Remaining work for simple predicates:

- [ ] Disallow question removal from a program if the program has a block with a predicate that depends on that question (should look similar to the reordering block warning - error toast)
- [ ] Display the current predicate on the Block Edit view
  - [ ] Would be good to have a pretty-printing function that can be used on both that page and on the predicate page itself
- [ ] Add a "remove/clear predicate" button on the predicates page
- [ ] JS that controls the Value input: if it's a number, we should show an input with type="number" and likewise for date type="date".
- [ ] Add "Edit predicates" link/button to Block Edit view
- [ ] Browser tests

**Comment by lianne-oy** [comment]
Should be done today / tomorrow

**Comment by baipai** [comment]
Working on the ux design part.

**Comment by natsid** [comment]
Un-assigning myself and @carolinedanzi from this task as #1532 now exists to capture all the work we did for establishing the predicate framework and implementing simple predicates.
