### ISSUE TITLE
Specify which scalars (i.e. sub-fields) of a question are optional vs. required

### ISSUE THREAD

**Issue by carolinedanzi** [seattle-uat/civiform#551]
**Describe the solution you'd like**
Currently, all scalars (aka sub-fields) of a question are required. However, this is not always desired - for example, not everyone has a middle name, so requiring an answer for the `middle` scalar on NameQuestionDefinition is not ideal.

Instead, we should create a way to indicate which scalars are actually required - this may be on a per-type basis, or perhaps we will allow admins to specify optional logic in question configurations (UX working to evaluate a solution here).

When implemented, we need to change the `Block` completion logic to only look at required scalar paths when determining `isComplete`. A Block can still be complete if an applicant chose not to answer optional scalars.

**Additional context**
Note: question metadata (currently program ID and last updated time) should always be required.

**Done when**
Each question definition specifies which of its scalars are required, and `Block`s can determine their own completion by checking only required scalar paths.

**Comment by kendrickt** [comment]
Each question type implements `PresentsErrors` and is responsible for `isAnswered()` and `getQuestionErrors()`. These methods can be used to present an error when a required field is missing. For example, in the name question the first and last name are required, so

`if (isAnswered() && isMissingFirstName()) { then error }` and 
`if (isAnswered() && isMissingLastName()) { then error }`. But there wouldn't be a check for the middle name because it is optional. 

Currently this is done on a case-by-case basis. There's no special annotation or way to mark optional vs required scalars for a question.
