### ISSUE TITLE
Bug: when Civiform admin clicks to add/remove question, changes to block name and description are thrown out

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#995]
If a Civiform admin is working on a form and changes the block name or description and then clicks to add/remove a question, the changes they made to the block name or description are thrown out. We should ensure that the block changes get saved/updated when the admin adds or removes a question to the block.

**Comment by kendrickt** [comment]
Related to #291

**Comment by kendrickt** [comment]
Proposed Solution: 

Every action on this page is an atomic form submission, so we'll make the block name/description edit atomic by using a modal that forces the admin to save it. Then everything on this view will behave the same, and changes cannot be thrown out because 
block name/description changes are saved before any other action is allowed.

**Comment by neel-a-mehta** [comment]
That works!

**Comment by lianne-oy** [comment]
Ready for story acceptance @neel-a-mehta

**Comment by neel-a-mehta** [comment]
The block metadata editor is now modal, so this is no longer a problem!

![image](https://user-images.githubusercontent.com/77128518/121080689-bda46480-c7a9-11eb-9854-d2a63d492e90.png)
